### ISSUE TITLE
Explainer: Mastodon Resource Usage

### ISSUE THREAD

**Issue by psaunders** [fedihost-co/articles#7]
Article explaining mastodons unusual resource usage and how it makes it hard to know exactly what instance size a group of users will need.
- [ ] The base worker threads
- [ ] What those threads do
- [ ] Ruby on rails and resource usage (Is it rails fault?)
- [ ] What makes resource usage high per user
- [ ] If a user follows from a popular instance, do they draw more on the server?

**Comment by vorboyvo** [comment]
Resource usage types covered
- [ ] CPU usage
- [ ] Memory usage
- [ ] Disk space usage

**Comment by vorboyvo** [comment]
> Article Structure:
> ## Resource Usage Factors
> ### Worker Threads
> 
> There are idling threads that have a base load overhead
> ### User Follows
> 
> Does following a lot of users increase resource usages? Which resources?
> ### Following Users
> 
> Does following a lot of users increase resource usages? Which resources?

I'd like to change the resource usage factors a bit:
- Base (all Mastodon instances)
- Local users
- User follow relationships
  - local
  - remote
- relay membership

I also want to include a brief explainer on how Mastodon allocates its resources behind the scenes. Not sure if I'll put it before or after the factors, depends on what makes the most sense. I want to talk about the Sidekiq queues but in an approachable manner. That way, we can hit the big point of: what happens when you run out of resources? what's the first to fail? how is user experience impacted by having limited resources?

**Comment by vorboyvo** [comment]
Committed to the branch, but this needs more work.
The article is too unfocused as is (is the article what the title says it is? no) and possibly needs to be split into several different articles or cleaned up.
